server:
  port: 8003
  
spring:
  application:
    name: sample-service
    
  jpa:
    hibernate:
      ddl-auto: update

    
  datasource:
    url: jdbc:mysql://0.0.0.0:3306/test
    username: root
    password: root@123
  cloud:
    config:
      uri:
      - http://localhost:8888
      enabled: true
    bus:
      enabled: true
      refresh:
        enabled: true  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
   
#sample:
#  prop: SomeData    

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
 
