server:
  port: 7001

spring:
  application:
    name: gateway-service
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8700/eureka/
  instance:
    hostname: localhost
    
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services:
  - '*'
  routes:
    resource-service:
      path: /resource/**
      service-id: resource-service
      strip-prefix: true
    sample-service:
      path: /users/**
      service-id: sample-service
      strip-prefix: true

  