server:
  port: 8081
  
 
spring:
  application:
    name: eureka-client-ribbon
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8700/eureka

